export const assets = [
    
    {url:"./WalkingWolf/walk1.png", name:"walkingWolf1"},
    {url:"./WalkingWolf/walk2.png", name:"walkingWolf2"},
    {url:"./WalkingWolf/walk3.png", name:"walkingWolf3"},
    {url:"./WalkingWolf/walk4.png", name:"walkingWolf4"},

    {url:"./ScoreBoardUtils/GlassPanel.png", name:"scoresPanel"},
    {url:"./ScoreBoardUtils/MetalPanelRed.png", name:"Board"},

    {url:"./ScoreBoardUtils/BlackCircle1.png", name:"BfirstPlace"},
    {url:"./ScoreBoardUtils/BlackCircle2.png", name:"BsecondPlace"},
    {url:"./ScoreBoardUtils/BlackCircle3.png", name:"BthirdPlace"},
    {url:"./ScoreBoardUtils/BlackCross.png", name:"BExit"},
    {url:"./ScoreBoardUtils/EmptyStar.png", name:"emptyStar"},
    {url:"./ScoreBoardUtils/BlackMusicOn.png", name:"BmusicOn"},
    {url:"./ScoreBoardUtils/BlackReturn.png", name:"BrePlay"},
    {url:"./ScoreBoardUtils/Star.png", name:"Star"},
    {url:"./ScoreBoardUtils/WhiteCross.png", name:"WExit"},
    {url:"./ScoreBoardUtils/SmallCross.png", name:"SExit"},
    {url:"./ScoreBoardUtils/WhiteMusicOn.png", name:"WmusicOn"},
    {url:"./ScoreBoardUtils/WhiteMusicOff.png", name:"WmusicOff"},
    {url:"./ScoreBoardUtils/WhiteReturn.png", name:"WrePlay"},
    {url:"./ScoreBoardUtils/SmallMusicOn.png", name:"SmusicOn"},
    {url:"./ScoreBoardUtils/SmallMusicOff.png", name:"SmusicOff"},
    {url:"./ScoreBoardUtils/SmallReturn.png", name:"SrePlay"},
    
    {url:"./Larry/walkLarry1.png", name:"walkLarry1"},
    {url:"./Larry/walkLarry2.png", name:"walkLarry2"},
    {url:"./Larry/walkLarry3.png", name:"walkLarry3"},
    {url:"./Larry/walkLarry4.png", name:"walkLarry4"},
    {url:"./Larry/walkLarry5.png", name:"walkLarry5"},
    {url:"./Larry/walkLarry6.png", name:"walkLarry6"},
    {url:"./Larry/idleLarry.png", name:"idleLarry"},
    {url:"./Larry/crouchLarry3.png", name:"crouchLarry3"},
    {url:"./Larry/crouchLarryReversed.png", name:"crouchLarryReversed"},
];