export const assets = [
    
    {url:"./WalkingWolf/walk1.png", name:"walkingWolf1"},
    {url:"./WalkingWolf/walk2.png", name:"walkingWolf2"},
    {url:"./WalkingWolf/walk3.png", name:"walkingWolf3"},
    {url:"./WalkingWolf/walk4.png", name:"walkingWolf4"},
    {url:"./Majora.png", name:"majora"},

    {url:"./ScoreBoardUtils/GlassPanel.png", name:"scoresPanel"},
    {url:"./ScoreBoardUtils/MetalPanelRed.png", name:"Board"},

    {url:"./ScoreBoardUtils/BlackCircle1.png", name:"BfirstPlace"},
    {url:"./ScoreBoardUtils/BlackCircle2.png", name:"BsecondPlace"},
    {url:"./ScoreBoardUtils/BlackCircle3.png", name:"BthirdPlace"},
    {url:"./ScoreBoardUtils/BlackCross.png", name:"BExit"},
    {url:"./ScoreBoardUtils/EmptyStar.png", name:"emptyStar"},
    {url:"./ScoreBoardUtils/BlackMusicOn.png", name:"BmusicOn"},
    {url:"./ScoreBoardUtils/BlackMusicOff.png", name:"BmusicOff"},
    {url:"./ScoreBoardUtils/BlackReturn.png", name:"BrePlay"},
    {url:"./ScoreBoardUtils/Star.png", name:"Star"},
    {url:"./ScoreBoardUtils/WhiteCross.png", name:"WExit"},
    {url:"./ScoreBoardUtils/SmallCross.png", name:"SExit"},
    {url:"./ScoreBoardUtils/WhiteMusicOn.png", name:"WmusicOn"},
    {url:"./ScoreBoardUtils/WhiteMusicOff.png", name:"WmusicOff"},
    {url:"./ScoreBoardUtils/WhiteReturn.png", name:"WrePlay"},
    {url:"./ScoreBoardUtils/SmallMusicOn.png", name:"SmusicOn"},
    {url:"./ScoreBoardUtils/SmallMusicOff.png", name:"SmusicOff"},
    {url:"./ScoreBoardUtils/SmallReturn.png", name:"SrePlay"},
    
    {url:"./Larry/walkLarry1.png", name:"walkLarry1"},
    {url:"./Larry/walkLarry2.png", name:"walkLarry2"},
    {url:"./Larry/walkLarry3.png", name:"walkLarry3"},
    {url:"./Larry/walkLarry4.png", name:"walkLarry4"},
    {url:"./Larry/walkLarry5.png", name:"walkLarry5"},
    {url:"./Larry/walkLarry6.png", name:"walkLarry6"},
    {url:"./Larry/idleLarry.png", name:"idleLarry"},
    {url:"./Larry/crouchLarry3.png", name:"crouchLarry3"},
    {url:"./Larry/crouchLarryReversed.png", name:"crouchLarryReversed"},
    {url:"./Larry/jumpLarry1.png", name:"jumpLarry1"},
    {url:"./Larry/jumpLarry2.png", name:"jumpLarry2"},
    {url:"./Larry/jumpLarry3.png", name:"jumpLarry3"},
    {url:"./Larry/verticalSlash1.png", name:"groundAttack1"},
    {url:"./Larry/verticalSlash2.png", name:"groundAttack2"},
    {url:"./Larry/verticalSlash3.png", name:"groundAttack3"},
    {url:"./Larry/verticalSlash4.png", name:"groundAttack4"},

    {url:"./Enemies/idlePeon.png", name:"idlePeon"},
    {url:"./Enemies/walkingPeon1.png", name:"walkingPeon1"},
    {url:"./Enemies/walkingPeon2.png", name:"walkingPeon2"},
    {url:"./Enemies/walkingPeon3.png", name:"walkingPeon3"},
    {url:"./Enemies/walkingPeon4.png", name:"walkingPeon4"},
    {url:"./Enemies/walkingPeon5.png", name:"walkingPeon5"},
    {url:"./Enemies/walkingPeon6.png", name:"walkingPeon6"},

    {url:"./Frostwoods/FullBackground.png", name:"FullBackground"},
    {url:"./Frostwoods/Background1.png", name:"Background1"},
    {url:"./Frostwoods/Background2.png", name:"Background2"},
    {url:"./Frostwoods/Background3.png", name:"Background3"},
    {url:"./Frostwoods/Background4.png", name:"Background4"},
    {url:"./Frostwoods/Background5.png", name:"Background5"},
    {url:"./Frostwoods/Background6.png", name:"Background6"},
    {url:"./Frostwoods/Background7.png", name:"Background7"},
];