export const assets = [
    
    {url:"./UI/Board.png", name:"Board"},
    {url:"./UI/BoardTittle.png", name:"Tittle"},
    {url:"./UI/normalButton.png", name:"normal"},
    {url:"./UI/overButton.png", name:"over"},
    {url:"./UI/downButton.png", name:"down"},
    {url:"./UI/textWindow.png", name:"textWindow"},

    {url:"./SFX&Music/EnemyExplosion.wav", name:"EnemyExplosion"},
    {url:"./SFX&Music/powerUp.wav", name:"PowerUp"},
    {url:"./SFX&Music/Select.wav", name:"Select"},
    {url:"./SFX&Music/SsExplosion.wav", name:"SsExplosion"},
    {url:"./SFX&Music/SsLaser.wav", name:"SsLaser"},
    {url:"./SFX&Music/Level1Music.mp3", name:"Level1Music"},
    {url:"./SFX&Music/Level2Music.mp3", name:"Level2Music"},
    {url:"./SFX&Music/MainMenuMusic.mp3", name:"MainMenuMusic"},
    {url:"./SFX&Music/GameOverMusic.mp3", name:"GameOverMusic"},
    {url:"./SFX&Music/BossBattle1.mp3", name:"BossBattle1"},
    {url:"./SFX&Music/BossBattle2.mp3", name:"BossBattle2"},
    {url:"./SFX&Music/BossExplosion.mp3", name:"BossExplosion"},

    {url:"./TextStyles/PixelStyle.ttf", name: "PixelFont"},

    {url:"/Backgrounds/levelBackground.png", name: "background"},
    {url:"/Backgrounds/MainMenuBack.png", name: "MainMenuBack"},
    {url:"/Backgrounds/GameOverBackground.png", name: "GameOverBack"},

    {url:"/Spaceships/Spaceship3.json", name: "Spaceship3"},
    {url:"/Spaceships/SsNFlight.json", name: "SsNFlight"},
    {url:"/Spaceships/SsTFlight.json", name: "SsTFlight"},
    {url:"/Spaceships/SsShots.json", name: "SsShots"},
    {url:"/Explosions/Explosions.json", name: "Explosions"},
    {url:"/Explosions/Explosions2.json", name: "Explosions2"},
    {url:"/Explosions/Explosions3.json", name: "Explosions3"},
    {url:"/Explosions/MegaExplosion.json", name: "MegaExplosion"},
    {url:"/EnemyShips/Boss1.png", name: "Boss1"},
    {url:"/EnemyShips/Boss1hit.png", name: "Boss1hit"},
    {url:"/EnemyShips/ExplodingBoss1.json", name: "ExplodingBoss1"},
    {url:"/EnemyShips/Enemies.json", name: "Enemies"},
    {url:"/EnemyShips/ProyectilesBoss1.json", name: "ProyectilesBoss1"},
    {url:"/EnemyShips/ProyectilesBoss2.json", name: "ProyectilesBoss2"},
    {url:"/Miscellaneous/Misc1.json", name: "Misc1"},
    {url:"/Miscellaneous/Misc2.json", name: "Misc2"},

];